#!/bin/bash

set -e

        #USER_UID=$(id -u)
        #USER_GID=$(id -g)
        xhost +local:podman

sudo podman run --rm \
        --privileged \
        --net host \
        --memory 1G \
        --cpuset-cpus 0 \
        --group-add $(getent group audio | cut -d: -f3) \
        --ipc=host \
        -e USER_UID=1000 \
        -e USER_GID=1000 \
        -e DISPLAY=$DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /var/run/dbus:/var/run/dbus \
        -v /run/user/1000/pulse/native:/run/pulse/native \
        --device /dev/snd \
        --name popcorntime \
        jmardz/popcorntime
